server:
  port: 18085
spring:
  profiles:
    active: dev
  application:
    name: search
  data:
    elasticsearch:
      cluster-name: lite-travel
      cluster-nodes: 49.235.197.94:9300
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
feign:
  hystrix:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 600000
# ribbon和hystrix的超时设置
ribbon:
  ReadTimeOut: 300000
hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
