spring:
  datasource:
    url: jdbc:mysql://122.51.98.193:3306/travel_database?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka