server:
  port: 18082
spring:
  profiles:
    active: prod # 默认为生产环境, 而测试运行时需要在运行虚拟机参数中设置为dev
  application:
    name: hotel
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 888666
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
eureka:
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 600000
# ribbon和hystrix的超时设置
ribbon:
  ReadTimeOut: 300000
hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.LiteTravel.hotel.pojo