spring:
  datasource:
    url: jdbc:mysql://172.18.0.8:3306/travel_database?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
eureka:
  client:
    service-url:
      defaultZone: http://172.16.0.4:7001/eureka